# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 11.3.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      
      - run:
          name: Build and run tests
          command: bundle exec fastlane $FASTLANE_LANE
          environment:
            SCAN_DEVICE: iPhone 11
            SCAN_SCHEME: TestCICD
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan


workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test
